spring:
  kafka:
    bootstrap-servers: kafka:9092 # Sửa localhost thành tên service kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer