spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: stat-group
      auto-offset-reset: earliest

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest